version: '3.7'
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:delegated
      - ~/.aws:/root/.aws
    command: "sleep infinity"
